sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install pytest-cov"
  - "pip install -e ."
script:
  - "python -m pytest --cov mercantile --cov-report term-missing"
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: mapboxci
